spring.application.name=hospital-management-system
server.port=${SERVER_PORT:8080}

# TiDB Cloud is MySQL compatible, so we use the MySQL JDBC driver.
# Recommended local env var:
# TIDB_DATABASE_URL=jdbc:mysql://HOST:4000/hospital_db?sslMode=VERIFY_IDENTITY&createDatabaseIfNotExist=true
spring.datasource.url=${TIDB_DATABASE_URL:jdbc:mysql://gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/hospital_db?sslMode=VERIFY_IDENTITY&createDatabaseIfNotExist=true}
spring.datasource.username=${TIDB_USERNAME:2yiR89yMy5Zfda5.root}
spring.datasource.password=${TIDB_PASSWORD:9CEDZ7CHOqUExIdl}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# The React dev server runs on port 5173 by default.
app.cors.allowed-origin=*


# Demo login credentials. Change these before deploying.
app.security.admin-username=${ADMIN_USERNAME:admin}
app.security.admin-password=${ADMIN_PASSWORD:admin123}

# Helpful for session cookies during local frontend/backend development.
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax
